### ISSUE TITLE
private channel stream

### ISSUE THREAD

**Issue by tacotokyo** [bitbankinc/bitbank-api-docs#11]
It would be great if you can add private channels. Major Japanese exchanges now implemented this feature. It reduces rest calls and much better UX for API traders.

https://bf-lightning-api.readme.io/docs/realtime-child-order-events
https://api.coin.z.com/docs/#ws-execution-events
https://developers.liquid.com/#private-channels
https://docs.ftx.com/#private-channels
https://binance-docs.github.io/apidocs/spot/en/#payload-order-update

**Comment by eckozen84** [comment]
Yes, I want this functionality too. I make a lot of periodic rest calls to fetch my balance which would be unnecessary if there was a private channel stream.

A side note, there is an alarming lack of communication on the github issues that have been raised about your API. As traders on your platform, we can only expect that the fees we pay go toward improving your system, otherwise there are better exchanges out there with much better functionality and similar fee structure.

**Comment by soichirokodama** [comment]
Sorry for the late reply.

Thanks for raising the issue.

For future feature requests, please contact us from the support page.

We'll investigate it using provided information.

https://support.bitbank.cc/hc/ja/requests/new
